#!/bin/bash

echo "hello 1" > /proc/demomodule
echo "hello 2" > /proc/demomodule
echo "hello 3" > /proc/demomodule
echo "world 4" > /proc/demomodule
echo "world 5" > /proc/demomodule
echo "world 6" > /proc/demomodule

echo "read 1:"
head -1 /proc/demomodule
echo "read 2:"
head -1 /proc/demomodule
echo "read 3:"
head -1 /proc/demomodule
echo "read 4:"
head -1 /proc/demomodule
echo "read 5:"
head -1 /proc/demomodule
echo "read 6:"
head -1 /proc/demomodule
echo "read 7:"
head -1 /proc/demomodule
